### PR TITLE
Bug fix to seat code and additional documentation

### PR DESCRIPTION
**Pull request by tnelson-integral**
This code fixes a few bugs identified in .tif generations for classified output and adds output. Documentation was added for a tutorial and overview, however I am having difficulty generating a new index.
-Tim

### CODE REVIEW

**Comment by ssolson** [comment]
@tnelson-integral I see you marked this PR as a draft but also tagged me for a review. 

Is this PR ready for review or are you still working on it?

**Comment by tnelson-integral** [comment]
@ssolson, it is ready for review, I am aware of some errors regarding the documentation formatting that I could use your revisions on. Let me know if I need to change the status of this request for that to happen.

**Comment by ssolson** [comment]
Okay Thanks Tim! 

I took a look at this last night and I saw nothing that prevent moving this forward. I go through it one more time and get it merged today.

Going forward we should talk strategy for working together. For example breaking this PR into 2 PRs: 1 for the bug fix and 1 for the documentation (this streamlines the review process). And then on the documentation we should coordinate because I have an open PR. The idea would be to both work on the same branch or coordinate specific sections to work on so that there is not rework and work that gets deprecated from moving things around ect. I can merge our work together no problem this time but PR #11 I had already changed some of the files that you also changed and our coordination will reduce this rework and work to then pick which version of the file is the final.

**Review by ssolson — COMMENTED** [review]
Tim I have a couple of thoughts I have commented in the code but neither are critical.

What I believe is critical is reducing the image size in this PR which is looking to add about 66 MBs. Images on Website should typically be less than 500 kB and a number of these are well over a MB. I wrote a script and tested it out and got these images from  multiple MBs to ~150 kB using the newer webp format. 

I could make the commit myself but I figured this would be useful to share incase in the future you need to reduce the image size.  I ran this file from the media folder. I also do not delete the original images which we need to after ensuring we are happy with the output

compress.py
```python
import os
from PIL import Image

# Directory containing the images
image_directory = '.'

# Desired maximum file size in kB
max_file_size_kb = 500


def compress_image(image_path, output_path, quality=85):
    """
    Compress the image and save it to output_path.
    The quality parameter controls the quality of the compression.
    Lowering the quality value will decrease the file size.
    """
    image = Image.open(image_path).convert(
        'RGB')  # Ensure the image is in RGB mode
    max_width = 1000
    width_percent = (max_width / float(image.size[0]))
    height_size = int((float(image.size[1]) * float(width_percent)))
    resized_img = image.resize((max_width, height_size), Image.ANTIALIAS)

    resized_img.save(output_path, 'WEBP', quality=quality)


def main():
    for filename in os.listdir(image_directory):
        if filename.endswith('.png'):
            print(f"Processing {filename}...")
            file_path = os.path.join(image_directory, filename)
            output_path = os.path.splitext(file_path)[0] + '.webp'

            # Get initial file size in kB
            initial_file_size_kb = os.path.getsize(file_path) / 1024
            print(f"{filename}: Initial Size: {initial_file_size_kb:.2f} kB")

            if initial_file_size_kb > max_file_size_kb:
                compress_image(file_path, output_path)

                # Get final file size in kB
                final_file_size_kb = os.path.getsize(output_path) / 1024
                print(
                    f"{os.path.basename(output_path)}: Final Size: {final_file_size_kb:.2f} kB\n")


if __name__ == "__main__":
    main()

```

Could you try this out for me and submit a commit with the latest images?

**Comment by ssolson** [comment]
@tnelson-integral 

I took care of all the changes above here https://github.com/ssolson/seat-qgis-plugin/pull/2

This PR is now included in #11

**Pull request closed without merging**
